x-postgres-db: &postgres-db
  image: ghcr.io/opexdev/postgres-opex
  environment:
    - POSTGRES_USER=${DB_USER:-opex}
    - POSTGRES_PASSWORD=${DB_PASS:-hiopex}
    - POSTGRES_DB=${DB_USER:-opex}
    - POSTGRES_READ_ONLY_USER=${DB_READ_ONLY_USER:-opex_reader}
    - POSTGRES_READ_ONLY_PASSWORD=${DB_READ_ONLY_PASS:-hiopex}
  networks:
    - default
  deploy:
    restart_policy:
      condition: on-failure

version: '3.8'
services:
  vault:
    image: ghcr.io/opexdev/vault-opex
    volumes:
      - vault-data:/vault/file
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - PANEL_PASS=${PANEL_PASS}
      - BACKEND_USER=${BACKEND_USER}
      - DB_USER=${DB_USER:-opex}
      - DB_PASS=${DB_PASS:-hiopex}
      - DB_READ_ONLY_USER=${DB_READ_ONLY_USER:-opex_reader}
      - DB_READ_ONLY_PASS=${DB_READ_ONLY_PASS:-hiopex}
      - VANDAR_API_KEY=$VANDAR_API_KEY
    cap_add:
      - IPC_LOCK
  vault-ui:
    image: djenriquez/vault-ui
    environment:
      - VAULT_URL_DEFAULT=http://vault:8200
      - VAULT_AUTH_DEFAULT=USERNAMEPASSWORD
    depends_on:
      - vault
  consul:
    image: consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
  postgres-payment:
    <<: *postgres-db
    volumes:
      - payment-data:/var/lib/postgresql/data/
  payment:
    image: ghcr.io/opexdev/payment
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DB_IP_PORT=postgres-payment
      - BACKEND_USER=${BACKEND_USER}
      - VAULT_HOST=vault
      - CONSUL_HOST=consul
    networks:
      - default
    depends_on:
      - consul
      - vault
      - postgres-payment
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  payment-data:
  vault-data:
networks:
  default:
    driver: bridge
