x-postgres-db: &postgres-db
  image: ghcr.io/opexdev/postgres-opex
  environment:
    - POSTGRES_USER=${DB_USER:-opex}
    - POSTGRES_PASSWORD=${DB_PASS:-hiopex}
    - POSTGRES_DB=${DB_USER:-opex}
    - POSTGRES_READ_ONLY_USER=${DB_READ_ONLY_USER:-opex_reader}
    - POSTGRES_READ_ONLY_PASSWORD=${DB_READ_ONLY_PASS:-hiopex}
  networks:
    - default
  deploy:
    restart_policy:
      condition: on-failure

version: '3.8'
services:
  consul:
    image: hashicorp/consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - default
      - otc-network
    deploy:
      restart_policy:
        condition: on-failure
  postgres-payment:
    <<: *postgres-db
    volumes:
      - payment-data:/var/lib/postgresql/data/
  payment:
    image: ghcr.io/opexdev/payment
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DB_IP_PORT=postgres-payment
      - BACKEND_USER=${BACKEND_USER}
      - VAULT_HOST=vault
      - CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=otc
      - auth_url=${AUTH_URL}
      - auth_jwk_endpoint=${JWK_ENDPOINT}
      - zarinpal_api_key=${ZARINPAL_API_KEY}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CLIENT_ID=${CLIENT_ID}
    networks:
      - default
      - otc-network
    depends_on:
      - consul
      - postgres-payment
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  payment-data:
  vault-data:
networks:
  default:
    driver: bridge
  otc-network:
    external: true
