version: '3.8'
services:
  postgres-payment:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-opex}
      - POSTGRES_PASSWORD=${DB_PASS:-hiopex}
      - POSTGRES_DB=opex_payment
      - POSTGRES_BACKUP_USER=${DB_BACKUP_USER:-opex_backup}
      - POSTGRES_BACKUP_PASSWORD=${DB_BACKUP_PASS:-hiopex}
    volumes:
      - ./resources/postgres/init-backup-user.sh:/docker-entrypoint-initdb.d/init-backup-user.sh
      - $DATA/opex-payment-data:/var/lib/postgresql/data/
    networks:
      - default
  payment:
    build:
      context: ./app
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044
      - SPRING_PROFILES_ACTIVE=docker
      - DB_IP_PORT=postgres-payment
      - BACKEND_USER=${BACKEND_USER}
      - VAULT_HOST=vault
      - CONSUL_HOST=consul
    networks:
      - default
    depends_on:
      - postgres-payment
    deploy:
      restart_policy:
        condition: on-failure
networks:
  default:
    name: ${DEFAULT_NETWORK_NAME:-opex}
    driver: bridge
