version: '3.8'
services:
  postgres-payment:
    image: "postgres"
    environment:
      - POSTGRES_USER=opex
      - POSTGRES_PASSWORD=hiopex
      - POSTGRES_DB=opex_payment
    volumes:
      - $DATA/opex-payment-data:/var/lib/postgresql/data/
    networks:
      - default
  payment:
    build:
      context: ./app
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044
      - SPRING_PROFILES_ACTIVE=docker
      - DB_IP_PORT=postgres-payment
      - VANDAR_API_KEY=${VANDAR_API_KEY}
    networks:
      - default
    depends_on:
      - postgres-payment
    deploy:
      restart_policy:
        condition: on-failure
networks:
  default:
    name: ${DEFAULT_NETWORK_NAME:-opex}
    driver: bridge