version: '3.8'
services:
  vault:
    image: ghcr.io/opexdev/vault-opex
    volumes:
      - vault-data:/vault/file
    environment:
      - VAULT_ADDRESS=http://0.0.0.0:8200
      - PANEL_PASS=${PANEL_PASS}
      - BACKEND_USER=${BACKEND_USER}
      - SMTP_PASS=${SMTP_PASS}
      - DB_USER=${DB_USER:-opex}
      - DB_PASS=${DB_PASS:-hiopex}
      - DB_BACKUP_USER=${DB_BACKUP_USER:-opex_backup}
      - DB_BACKUP_PASS=${DB_BACKUP_PASS:-hiopex}
      - KEYCLOAK_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME:-opex-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-hiopex}
      - OPEX_ADMIN_KEYCLOAK_CLIENT_SECRET=${OPEX_ADMIN_KEYCLOAK_CLIENT_SECRET}
      - VANDAR_API_KEY=$VANDAR_API_KEY
    healthcheck:
      retries: 5
    cap_add:
      - IPC_LOCK
  vault-ui:
    image: djenriquez/vault-ui
    environment:
      - VAULT_URL_DEFAULT=http://vault:8200
      - VAULT_AUTH_DEFAULT=USERNAMEPASSWORD
    depends_on:
      - vault
  consul:
    image: consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
  postgres-payment:
    image: ghcr.io/opexdev/postgres-opex
    environment:
      - POSTGRES_USER=${DB_USER:-opex}
      - POSTGRES_PASSWORD=${DB_PASS:-hiopex}
      - POSTGRES_DB=opex_payment
      - POSTGRES_BACKUP_USER=${DB_BACKUP_USER:-opex_backup}
      - POSTGRES_BACKUP_PASSWORD=${DB_BACKUP_PASS:-hiopex}
    volumes:
      - opex-payment-data:/var/lib/postgresql/data/
    networks:
      - default
  payment:
    image: ghcr.io/opexdev/payment
    environment:
      - JAVA_OPTS=-Xmx256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_PROFILES_ACTIVE=docker
      - DB_IP_PORT=postgres-payment
      - BACKEND_USER=${BACKEND_USER}
      - VAULT_HOST=vault
      - CONSUL_HOST=consul
    networks:
      - default
    depends_on:
      - postgres-payment
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  vault-data:
  opex-payment-data:
networks:
  default:
    driver: bridge