server.port: 8080
spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_IP_PORT:localhost}/opex_payment
    username: opex
    password: hiopex
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    co.nilin: DEBUG
    reactor.netty.http.client: DEBUG
app:
  opex:
    wallet-url: http://wallet:8080
    cert-url: http://auth:8080/auth/realms/opex/protocol/openid-connect/certs
  jibit-url: https://api.jibit.ir/ppg/v2
  vandar:
    api-key: ${VANDAR_API_KEY}
    ipg-url: https://ipg.vandar.io/api/v3
    redirect-url: https://ipg.vandar.io/v3
    data-url: https://vandar.io/api/ipg