name: Deploy Payment - Dev
on:
  push:
    branches:
      - dev
jobs:
  jenkinsJob:
    name: Deploy Payment
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Payment build job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "opex-ipg-dev"